
default:
	gcc ascii.c -D_GNU_SOURCE -Wall -std=c99 -pedantic -o ascii.x
	gcc binview.c -D_GNU_SOURCE -Wall -std=c99 -pedantic -o binview.x
	gcc errno.c -D_GNU_SOURCE -Wall -std=c99 -pedantic -o errno.x
	gcc signalList.c -D_GNU_SOURCE -Wall -std=c99 -pedantic -o signalList.x
	gcc tester.c -c -fPIC -D_GNU_SOURCE -I../../include -Wall -std=c99 -pedantic -o tester.o
